[package]
name = "eightball"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
conrod_core = "0.74.0"
conrod_glium = "0.74.0"
conrod_winit = "0.74.0"
glium = "0.28.0"